# Generated by Django 3.2 on 2021-05-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('notifications', '0002_notifications_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='profiles.profile'),
        ),
    ]
